// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1:string):Promise<string>;

export function CheckApiKey():Promise<boolean>;

export function FetchModels():Promise<string>;

export function GetConfig():Promise<string>;

export function GetCreatorName():Promise<string>;

export function GetGreet():Promise<string>;

export function GetHeartbeat():Promise<string>;

export function GetStatus():Promise<string>;

export function HasAPIKey():Promise<boolean>;

export function InitSelf():Promise<string>;

export function IsFirstRun():Promise<boolean>;

export function SaveApiKey(arg1:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetCreatorName(arg1:string):Promise<string>;

export function SetHeartbeatPhase(arg1:string,arg2:string):Promise<void>;

export function Shutdown():Promise<string>;

export function StartAutonomic():Promise<string>;
