// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function CheckApiKey() {
  return window['go']['main']['App']['CheckApiKey']();
}

export function FetchModels() {
  return window['go']['main']['App']['FetchModels']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCreatorName() {
  return window['go']['main']['App']['GetCreatorName']();
}

export function GetGreet() {
  return window['go']['main']['App']['GetGreet']();
}

export function GetHeartbeat() {
  return window['go']['main']['App']['GetHeartbeat']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function InitSelf() {
  return window['go']['main']['App']['InitSelf']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function SaveApiKey(arg1) {
  return window['go']['main']['App']['SaveApiKey'](arg1);
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetCreatorName(arg1) {
  return window['go']['main']['App']['SetCreatorName'](arg1);
}

export function SetHeartbeatPhase(arg1, arg2) {
  return window['go']['main']['App']['SetHeartbeatPhase'](arg1, arg2);
}

export function StartAutonomic() {
  return window['go']['main']['App']['StartAutonomic']();
}
